name=JSON_Manager
version=2.0.0
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=A robust wrapper for ArduinoJson and LittleFS tailored for ESP32 and ESP8266.
paragraph=This library simplifies reading, writing, and manipulating JSON configuration files in the flash memory of ESP microcontrollers. It prevents memory fragmentation and handles hardware/file system faults safely.
category=Data Processing
url=https://github.com/0ADILL3/JSON_Manager
architectures=esp8266,esp32
depends=ArduinoJson
includes=JSON_Manager.h